update for jetty 10
opentable/otj-metrics pull request #102
Opened 2022-12-02 03:58 UTC by jszczesnyoa

DO NOT MERGE

https://opentable.atlassian.net/browse/OTPL-6933

Running PR for updated to jetty 10:

- InstrumentedQueuedThreadPool updated, uses different package, also requires slf4j2
- jetty-server requires slfj2 as well
- javadoc update, also had to disable linting temporarily, seems to throw errors where it doesn't seem there should be
- excluded jetty-servlet-api 2nd, 3rd, 4th nth try

2022-12-02 03:59 UTC, jszczesnyoa commented on pom.xml
> +        <version>358-SNAPSHOT</version>
i'll change this

2022-12-02 16:11 UTC, mikebell90 commented on pom.xml
> +        <basepom.check.fail-dependency>false</basepom.check.fail-dependency>
Obviously you want to remove most of these.

2022-12-08 00:35 UTC, dkaukov requested changes

2022-12-08 00:35 UTC, dkaukov commented on otj-metrics-core/src/main/java/com/opentable/metrics/graphite/OtGraphiteReporter.java
> +@SuppressWarnings("PMD.UseTryWithResources")
Can we actually fix that, instead of suppressing?

2023-03-13 16:49 UTC, mikebell90 approved these changes

2023-03-13 20:32 UTC, merged